// Theme definitions for YouTube Tools
// Used by theme engine to apply gradients and colors

export const THEMES = [
  {
    name: 'Default / Reload',
    gradient: '',
    textColor: '',
    raised: '',
    btnTranslate: '',
    CurrentProgressVideo: '',
    videoDuration: '',
    colorIcons: '',
    textLogo: '',
    glassBg: '',
    glassBlur: '',
  },
  {
    name: 'Midnight Blue',
    gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    textColor: '#ffffff',
    raised: '#f00',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(30, 58, 138, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Forest Green',
    gradient: 'linear-gradient(135deg, #14532d, #22c55e)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(20, 83, 45, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Sunset Orange',
    gradient: 'linear-gradient(135deg, #7c2d12, #f97316)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(124, 45, 18, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Royal Purple',
    gradient: 'linear-gradient(135deg, #2e1065, #4c1d95)',
    textColor: '#ffffff',
    raised: '#4c1d95',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(46, 16, 101, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Cherry Blossom',
    gradient: 'linear-gradient(135deg, #a9005c, #fc008f)',
    textColor: '#ffffff',
    raised: '#fc008f',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(169, 0, 92, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Red Dark',
    gradient: 'linear-gradient(135deg, #790909, #f70131)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(121, 9, 9, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Raind',
    gradient: 'linear-gradient(90deg, #3f5efb 0%, #fc466b 100%)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(63, 94, 251, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Neon',
    gradient: 'linear-gradient(273deg, #ee49fd 0%, #6175ff 100%)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(238, 73, 253, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Azure',
    gradient: 'linear-gradient(273deg, #0172af 0%, #74febd 100%)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(1, 114, 175, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Butterfly',
    gradient: 'linear-gradient(273deg, #ff4060 0%, #fff16a 100%)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(255, 64, 96, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Colombia',
    gradient: 'linear-gradient(174deg, #fbf63f 0%, #0000bb 45%, #ff0000 99%)',
    textColor: '#ffffff',
    raised: '#303131',
    btnTranslate: '#000',
    CurrentProgressVideo: '#0f0',
    videoDuration: '#fff',
    colorIcons: '#fff',
    textLogo: '#f00',
    glassBg: 'rgba(0, 0, 187, 0.5)',
    glassBlur: '20px',
  },
];
