// Theme definitions for YouTube Tools
// Used by theme engine to apply gradients and colors

export const THEMES = [
  {
    name: 'Default / Reload',
    gradient: '',
    textColor: '',
    raised: '',
    btnTranslate: '',
    CurrentProgressVideo: '',
    videoDuration: '',
    colorIcons: '',
    textLogo: '',
    glassBg: '',
    glassBlur: '',
  },
  {
    name: 'Midnight Blue',
    gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    textColor: '#ffffff',
    raised: 'rgba(30, 58, 138, 0.4)',
    btnTranslate: '#3b82f6',
    CurrentProgressVideo: '#60a5fa',
    videoDuration: '#bfdbfe',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(30, 58, 138, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Forest Green',
    gradient: 'linear-gradient(135deg, #14532d, #22c55e)',
    textColor: '#ffffff',
    raised: 'rgba(20, 83, 45, 0.4)',
    btnTranslate: '#22c55e',
    CurrentProgressVideo: '#4ade80',
    videoDuration: '#bbf7d0',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(20, 83, 45, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Sunset Orange',
    gradient: 'linear-gradient(135deg, #7c2d12, #f97316)',
    textColor: '#ffffff',
    raised: 'rgba(124, 45, 18, 0.4)',
    btnTranslate: '#f97316',
    CurrentProgressVideo: '#fb923c',
    videoDuration: '#ffedd5',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(124, 45, 18, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Royal Purple',
    gradient: 'linear-gradient(135deg, #2e1065, #4c1d95)',
    textColor: '#ffffff',
    raised: 'rgba(46, 16, 101, 0.4)',
    btnTranslate: '#4c1d95',
    CurrentProgressVideo: '#8b5cf6',
    videoDuration: '#ddd6fe',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(46, 16, 101, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Cherry Blossom',
    gradient: 'linear-gradient(135deg, #a9005c, #fc008f)',
    textColor: '#ffffff',
    raised: 'rgba(169, 0, 92, 0.4)',
    btnTranslate: '#fc008f',
    CurrentProgressVideo: '#ff49db',
    videoDuration: '#fbcfe8',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(169, 0, 92, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Red Dark',
    gradient: 'linear-gradient(135deg, #790909, #f70131)',
    textColor: '#ffffff',
    raised: 'rgba(121, 9, 9, 0.4)',
    btnTranslate: '#f70131',
    CurrentProgressVideo: '#ff4d4d',
    videoDuration: '#fecaca',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(121, 9, 9, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Raind',
    gradient: 'linear-gradient(90deg, #3f5efb 0%, #fc466b 100%)',
    textColor: '#ffffff',
    raised: 'rgba(63, 94, 251, 0.4)',
    btnTranslate: '#fc466b',
    CurrentProgressVideo: '#ff7eb9',
    videoDuration: '#e0e7ff',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(63, 94, 251, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Neon',
    gradient: 'linear-gradient(273deg, #ee49fd 0%, #6175ff 100%)',
    textColor: '#ffffff',
    raised: 'rgba(238, 73, 253, 0.4)',
    btnTranslate: '#6175ff',
    CurrentProgressVideo: '#a5b4fc',
    videoDuration: '#fae8ff',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(238, 73, 253, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Azure',
    gradient: 'linear-gradient(273deg, #0172af 0%, #74febd 100%)',
    textColor: '#ffffff',
    raised: 'rgba(1, 114, 175, 0.4)',
    btnTranslate: '#74febd',
    CurrentProgressVideo: '#a7f3d0',
    videoDuration: '#d1fae5',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(1, 114, 175, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Butterfly',
    gradient: 'linear-gradient(273deg, #ff4060 0%, #fff16a 100%)',
    textColor: '#ffffff',
    raised: 'rgba(255, 64, 96, 0.4)',
    btnTranslate: '#ff4060',
    CurrentProgressVideo: '#fecaca',
    videoDuration: '#fef3c7',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(255, 64, 96, 0.5)',
    glassBlur: '20px',
  },
  {
    name: 'Colombia',
    gradient: 'linear-gradient(174deg, #fbf63f 0%, #0000bb 45%, #ff0000 99%)',
    textColor: '#ffffff',
    raised: 'rgba(0, 0, 187, 0.4)',
    btnTranslate: '#0000bb',
    CurrentProgressVideo: '#ff4d4d',
    videoDuration: '#fef08a',
    colorIcons: '#ffffff',
    textLogo: '#ffffff',
    glassBg: 'rgba(0, 0, 187, 0.5)',
    glassBlur: '20px',
  },
];
